<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
	xmlns:tns="http://org.ow2.petals/demo/travelagency/agency/Artifacts"
	xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://org.ow2.petals/demo/travelagency/airline/"
	xmlns:wsdl1="http://org.ow2.petals/demo/travelagency/hotel/"
	xmlns:wsdl2="http://org.ow2.petals/demo/travelagency/agency/"
	xmlns:hotc="http://www.example.org/processHotelConfirmation/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="processArtifacts"
	targetNamespace="http://org.ow2.petals/demo/travelagency/agency/Artifacts">
	<plnk:partnerLinkType name="airlineLT">
		<plnk:role name="airlineRole" portType="wsdl:AirLineBook" />
	</plnk:partnerLinkType>
	<plnk:partnerLinkType name="hotelLT">
		<plnk:role name="hotelRole" portType="wsdl1:hotel" />
	</plnk:partnerLinkType>
	
 
	<import location="AirLineBookService.wsdl"
		namespace="http://org.ow2.petals/demo/travelagency/airline/" />
	<import location="hotel.wsdl"
		namespace="http://org.ow2.petals/demo/travelagency/hotel/" />
	<import location="process.wsdl"
		namespace="http://org.ow2.petals/demo/travelagency/agency/" />
</definitions>

